### ISSUE TITLE
Проблемы сборки

### ISSUE THREAD

**Issue by avasyukov** [Filatkin/Linal#2]
Предполагаю, что либо что-то не было запушено, либо перед пушем код не был проверен.

Сейчас всё выглядит очень правдоподобно, но банально не компилируется. Происходит это из-за тонны мелочей разной мелкости, все особо и не перечислить.

Сборку нужно пофиксить.

_(С учётом даты на календаре - фиксить будет разумно после 13го. Задача принята к сдаче. Но закопаться в ней можно ещё прилично. Есть смысл не тратить пока что на неё ценное время.)_

**Comment by Filatkin** [comment]
Fixed

**Comment by avasyukov** [comment]
Ок, починено
